#!/bin/bash

echo -e '[User]\nLanguage=\nXSession=gnome\nSystemAccount=true' > /var/lib/AccountsService/users/vanilla
echo '[daemon]' > /etc/gdm3/daemon.conf

REAL_USER=""

if [ -f "/tmp/new-user-name" ]; then
    REAL_USER=$(cat "/tmp/new-user-name")
else
    REAL_USER=$(getent passwd $PKEXEC_UID | sed 's/:.*//')
fi

echo -e '[User]\nSession=gnome' > /var/lib/AccountsService/users/$REAL_USER
