#!/bin/bash
if [ -z "$1" ]; then
    echo "usage:"
    echo "flatpak-uninstall <flatpak id>"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

flatpak uninstall --user -y "$1"
