#!/bin/bash
if [ -z "$1" ]; then
    echo "usage:"
    echo "flatpak <flatpak id>"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

flatpak install --user -y "$1"
