#!/bin/bash
# This sets the currently active keyboard in gnome, not the persistant system keyboard configuration
if [ -z "$1" ]; then
    echo "usage:"
    echo "live-keyboard <layout> [variant]"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

layout="$1"

if ! [ -z "$2" ]; then
    layout="$layout+$2"
fi

gsettings set org.gnome.desktop.input-sources sources "[('xkb', '$layout')]"
