#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "remove-autostart-file"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

rm ~/.config/autostart/org.vanillaos.FirstSetup.autostart.desktop
