#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "setup-flatpak-remote"
    exit 5
fi

if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
