#!/bin/bash
if [ -z "$1" ]; then
    echo "usage:"
    echo "timezone <timezone>"
    exit 5
fi

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 6
fi

echo "$1" > /etc/timezone
CODE_ONE="$?"
rm /etc/localtime
ln -sf "/usr/share/zoneinfo/$1" /etc/localtime
CODE_TWO="$?"

exit $(($CODE_ONE + $CODE_TWO))
