#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "usage:"
    echo "user <username> <full name>"
    exit 5
fi

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 6
fi

adduser --quiet --disabled-password --shell /bin/bash --gecos "$2" "$1"
passwd --delete --expire "$1"
usermod -a -G sudo,adm,lpadmin "$1"
