name: Build release packages
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-packages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      # Misc
      # --------------------------------------
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat VERSION)

      # Dependencies
      # --------------------------------------
      - name: Install build dependencies
        run: |
          sudo apt install -y debhelper python3 gettext build-essential desktop-file-utils ninja-build meson libadwaita-1-dev make

      # Deb Build
      # --------------------------------------
      - name: Build .deb package
        run: dpkg-buildpackage

      # Release packages
      # --------------------------------------        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
          title: ${{ steps.get_version.outputs.VERSION }}
          files: ../vanilla-first-setup_*.deb