name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it
    permissions:
      contents: read

    steps:
        - uses: actions/checkout@v4
  
        - name: Set meson version by tag
          id: set_version
          run: |
            sed -i 's/VTESTING/${{ github.ref_name }}/g' meson.build
  
        - name: Install build dependencies
          run: |
            apt-get update
            apt-get build-dep -y .
  
        - name: Build .deb package
          run: |
              dpkg-buildpackage
              mv ../vanilla-first-setup_*.deb vanilla-first-setup.deb
  
        - name: Calculate and Save Checksums
          run: |
            sha256sum vanilla-first-setup.deb >> checksums.txt
  
        - uses: actions/upload-artifact@v4
          with:
            name: first-setup
            path: |
                checksums.txt
                vanilla-first-setup.deb

  release:
    runs-on: ubuntu-latest
    needs: build-artifacts
    permissions:
      contents: write # to create and upload assets to releases
      attestations: write # to upload assets attestation for build provenance
      id-token: write # grant additional permission to attestation action to mint the OIDC token permission

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: first-setup

      - name: Create Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes vanilla-first-setup.deb checksums.txt
      
      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'vanilla-first-setup.deb, checksums.txt'
