name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it
    permissions:
      contents: read

    steps:
        - uses: actions/checkout@v4
  
        - name: Get the version
          id: get_version
          run: echo "{VERSION}={$(cat VERSION)}" >> $GITHUB_OUTPUT
  
        - name: Install build dependencies
          run: |
            apt install -y debhelper python3 gettext build-essential desktop-file-utils ninja-build meson libadwaita-1-dev make libnm-dev libnma-dev libnma-gtk4-dev
  
        - name: Build .deb package
          run: |
              dpkg-buildpackage
              mv ../vanilla-first-setup_*.deb .
  
        - name: Calculate and Save Checksums
          run: |
            sha256sum vanilla-first-setup_*.deb >> checksums.txt
  
        - uses: actions/upload-artifact@v4
          with:
            name: first-setup
            path: |
                checksums.txt
                vanilla-first-setup_*.deb

  release:
    runs-on: ubuntu-latest
    needs: build-artifacts
    permissions:
      contents: write # to create and upload assets to releases
      attestations: write # to upload assets attestation for build provenance
      id-token: write # grant additional permission to attestation action to mint the OIDC token permission

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: first-setup

      - name: Create Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes *.deb first-setup/checksums.txt
      
      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '*.deb, first-setup/*.txt'
