welcome = [
    'Welcome', 
    'Benvenuto', 
    'Bienvenido', 
    'Bienvenue', 
    'Willkommen', 
    'Bem-vindo', 
    'Добро пожаловать', 
    '欢迎', 
    'ようこそ', 
    '환영합니다', 
    'أهلا بك', 
    'ברוך הבא', 
    'Καλώς ήρθατε', 
    'Hoşgeldiniz', 
    'Welkom', 
    'Witamy', 
    'Välkommen', 
    'Tervetuloa', 
    'Vítejte', 
    'Üdvözöljük', 
    'Bun venit', 
    'Vitajte', 
    'Tere tulemast', 
    'Sveiki atvykę', 
    'Dobrodošli', 
    'خوش آمدید', 
    'आपका स्वागत है', 
    'স্বাগতম', 
    'வரவேற்கிறோம்', 
    'స్వాగతం', 
    'मुबारक हो', 
    'સુસ્વાગત છે', 
    'ಸುಸ್ವಾಗತ', 
    'സ്വാഗതം'
]